// <auto-generated />
using System;
using GitLabAWSKeyRotation.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitLabAWSKeyRotation.Infrastructure.Migrations
{
    [DbContext(typeof(GitLabAWSKeyRotationDbContext))]
    [Migration("20230414171955_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GitLabAWSKeyRotation.Domain.AWS.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("AccountId");

                    b.Property<string>("AwsAccountId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AWSAccounts", (string)null);
                });

            modelBuilder.Entity("GitLabAWSKeyRotation.Domain.GitLab.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("AccessTokenId");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TokenName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GitlabAccessTokens");
                });

            modelBuilder.Entity("GitLabAWSKeyRotation.Domain.GitLab.CodeRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("CodeRepositoryId");

                    b.Property<Guid>("AccessTokenId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenId");

                    b.ToTable("CodeRepository");
                });

            modelBuilder.Entity("GitLabAWSKeyRotation.Domain.AWS.Account", b =>
                {
                    b.OwnsMany("GitLabAWSKeyRotation.Domain.AWS.Entities.IAM", "IamIdentities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("IamId");

                            b1.Property<Guid>("AWSAccountId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("AccessKeyId")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("AccessSecret")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Arn")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<float>("KeyRotationInDays")
                                .HasColumnType("float");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("Id");

                            b1.HasIndex("AWSAccountId");

                            b1.ToTable("AWSIAMs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AWSAccountId");

                            b1.OwnsMany("GitLabAWSKeyRotation.Domain.GitLab.Rotation", "Rotations", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("char(36)")
                                        .HasColumnName("RotationDependentRepositoryVariablesId");

                                    b2.Property<string>("AccessKeyIdVariableName")
                                        .IsRequired()
                                        .HasColumnType("longtext");

                                    b2.Property<string>("AccessSecretVariableName")
                                        .IsRequired()
                                        .HasColumnType("longtext");

                                    b2.Property<Guid>("CodeRepositoryId")
                                        .HasColumnType("char(36)");

                                    b2.Property<string>("Environment")
                                        .IsRequired()
                                        .HasColumnType("longtext");

                                    b2.Property<Guid?>("IamId")
                                        .HasColumnType("char(36)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("CodeRepositoryId");

                                    b2.HasIndex("IamId");

                                    b2.ToTable("RotationDependentRepositoryVariables", (string)null);

                                    b2.HasOne("GitLabAWSKeyRotation.Domain.GitLab.CodeRepository", null)
                                        .WithMany()
                                        .HasForeignKey("CodeRepositoryId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("IamId");
                                });

                            b1.Navigation("Rotations");
                        });

                    b.Navigation("IamIdentities");
                });

            modelBuilder.Entity("GitLabAWSKeyRotation.Domain.GitLab.CodeRepository", b =>
                {
                    b.HasOne("GitLabAWSKeyRotation.Domain.GitLab.AccessToken", null)
                        .WithMany("CodeRepositories")
                        .HasForeignKey("AccessTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GitLabAWSKeyRotation.Domain.GitLab.AccessToken", b =>
                {
                    b.Navigation("CodeRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
